from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from langchain.agents import create_agent
from langchain.tools import tool
from langchain.tools.tool_node import ToolRuntime
from langchain_openai import ChatOpenAI

from ..core.models import ProjectPaths, UnitContext
from ..core.settings import AppSettings


@dataclass(slots=True)
class LLMGeneration:
    code: str
    rationale: str


@dataclass(slots=True)
class AgentArtifact:
    path: str
    content: str
    rationale: str


@dataclass(slots=True)
class AgentContext:
    paths: ProjectPaths


class LLMClient:
    def __init__(self, settings: AppSettings, paths: ProjectPaths) -> None:
        self.settings = settings
        self.paths = paths
        self.model = self._build_model()
        self.agent = self._build_agent()

    def generate_code(self, context: UnitContext) -> LLMGeneration:
        artifact = self._run_agent(self._build_migration_task(context))
        return LLMGeneration(code=artifact.content, rationale=artifact.rationale)

    def generate_tests(self, context: UnitContext, test_path: str) -> str:
        artifact = self._run_agent(self._build_test_task(context, test_path))
        return artifact.content

    def repair_artifact(
        self,
        context: UnitContext,
        failure_log: str,
        test_path: str,
    ) -> AgentArtifact | None:
        return self._run_agent(self._build_repair_task(context, failure_log, test_path))

    def _build_model(self) -> ChatOpenAI:
        if not self.settings.has_api_key:
            raise RuntimeError("Missing API key for LangChain agent model.")
        return ChatOpenAI(
            base_url=self.settings.base_url,
            api_key=self.settings.api_key,
            model=self.settings.model_name,
            temperature=0,
        )

    def _build_agent(self) -> Any:
        return create_agent(
            model=self.model,
            tools=_build_agent_tools(),
            system_prompt=(
                "You are a code migration agent. Use tools to inspect files and directories before writing output when needed. "
                "Your final response must be a structured artifact with path, content, and rationale. "
                "Python target modules must contain only runnable Python module code. "
                "Generated tests must be standalone unittest scripts and must not use pytest."
            ),
            response_format=AgentArtifact,
            context_schema=AgentContext,
        )

    def _run_agent(self, task: str) -> AgentArtifact:
        try:
            result = self.agent.invoke(
                {"messages": [{"role": "user", "content": task}]},
                context=AgentContext(paths=self.paths),
            )
        except Exception as exc:
            raise RuntimeError(f"LangChain agent invocation failed: {exc}") from exc
        artifact = result.get("structured_response")
        if isinstance(artifact, AgentArtifact):
            return artifact
        if isinstance(artifact, dict):
            return AgentArtifact(
                path=str(artifact["path"]),
                content=str(artifact["content"]),
                rationale=str(artifact.get("rationale", "Generated by LangChain agent.")),
            )
        raise RuntimeError("LangChain agent did not return a structured artifact.")

    def _build_migration_task(self, context: UnitContext) -> str:
        return (
            "Create the full updated content for the target module file.\n"
            f"Unit: {context.unit_id}\n"
            f"Summary: {context.summary}\n"
            f"Target path: {context.target_file_path}\n"
            f"Dependency summaries: {json.dumps(context.dependency_summaries, ensure_ascii=False)}\n"
            "Rules:\n"
            "- If the target file exists, read it and merge this unit into the module instead of returning prose.\n"
            "- Do not place tests or markdown into the target module.\n"
            "- Return the final full file content for the target path.\n\n"
            f"Source code:\n```python\n{context.source_code}\n```"
        )

    def _build_test_task(self, context: UnitContext, test_path: str) -> str:
        return (
            "Create a standalone test file for the migrated unit.\n"
            f"Unit: {context.unit_id}\n"
            f"Summary: {context.summary}\n"
            f"Target file: {context.target_file_path}\n"
            f"Test path: {test_path}\n"
            f"Test requirements: {json.dumps(context.test_requirements, ensure_ascii=False)}\n"
            "Rules:\n"
            "- Use unittest only.\n"
            "- The file must be runnable with `python <testfile>`.\n"
            "- Return the final full test file content for the test path.\n\n"
            f"Source code:\n```python\n{context.source_code}\n```"
        )

    def _build_repair_task(self, context: UnitContext, failure_log: str, test_path: str) -> str:
        return (
            "Repair the smallest failing file and return its full corrected content.\n"
            f"Unit: {context.unit_id}\n"
            f"Target file: {context.target_file_path}\n"
            f"Test file: {test_path}\n"
            "Rules:\n"
            "- Read the relevant existing file before editing.\n"
            "- Fix only one file per response.\n"
            "- Keep tests on unittest only.\n\n"
            f"Failure log:\n```text\n{failure_log[:3000]}\n```\n\n"
            f"Original source code:\n```python\n{context.source_code}\n```"
        )

def _build_agent_tools() -> list[Any]:
    @tool
    def list_dir(path: str, runtime: ToolRuntime[AgentContext]) -> str:
        """List entries under a directory path."""
        resolved = _resolve_path(path, runtime.context)
        entries = [
            {
                "name": child.name,
                "path": str(child),
                "type": "dir" if child.is_dir() else "file",
            }
            for child in sorted(resolved.iterdir(), key=lambda item: item.name)
        ]
        return json.dumps({"path": str(resolved), "entries": entries}, ensure_ascii=False)

    @tool
    def read_file(path: str, runtime: ToolRuntime[AgentContext]) -> str:
        """Read a UTF-8 text file."""
        resolved = _resolve_path(path, runtime.context)
        return resolved.read_text(encoding="utf-8")

    @tool
    def exists(path: str, runtime: ToolRuntime[AgentContext]) -> str:
        """Check whether a path exists."""
        resolved = _resolve_path(path, runtime.context)
        return json.dumps({"path": str(resolved), "exists": resolved.exists()}, ensure_ascii=False)

    @tool
    def mkdir(path: str, runtime: ToolRuntime[AgentContext]) -> str:
        """Create a directory path inside the project, workspace, or target roots."""
        resolved = _resolve_path(path, runtime.context)
        resolved.mkdir(parents=True, exist_ok=True)
        return str(resolved)

    @tool
    def write_file(path: str, content: str, runtime: ToolRuntime[AgentContext]) -> str:
        """Write a UTF-8 text file."""
        resolved = _resolve_path(path, runtime.context)
        resolved.parent.mkdir(parents=True, exist_ok=True)
        resolved.write_text(content, encoding="utf-8")
        return str(resolved)

    @tool
    def compile_python(path: str, runtime: ToolRuntime[AgentContext]) -> str:
        """Compile a Python file to check syntax."""
        resolved = _resolve_path(path, runtime.context)
        compile(resolved.read_text(encoding="utf-8"), str(resolved), "exec")
        return f"compiled:{resolved}"

    return [list_dir, read_file, exists, mkdir, write_file, compile_python]


def _resolve_path(raw_path: str, agent_context: AgentContext) -> Path:
    path = Path(raw_path)
    if not path.is_absolute():
        path = Path(agent_context.paths.source_root) / path
    resolved = path.resolve()
    allowed_roots = (
        Path(agent_context.paths.source_root).resolve(),
        Path(agent_context.paths.workspace_root).resolve(),
        Path(agent_context.paths.target_root).resolve(),
    )
    if not any(resolved == root or root in resolved.parents for root in allowed_roots):
        raise ValueError(f"path outside allowed roots: {resolved}")
    return resolved
